
package librarymanagementsystem.adminDashboard_Folder;


import librarymanagementsystem.manageBooks_Folder.*;


public class Manage_Books extends javax.swing.JFrame {
    
    
    
    public Manage_Books() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        addbook_btn = new javax.swing.JButton();
        updateBook_btn = new javax.swing.JButton();
        removeBook_btn = new javax.swing.JButton();
        searchBook_btn = new javax.swing.JButton();
        addbook_btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setText("Manage Books");

        back_btn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        addbook_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addbook_btn.setText("Add Book");
        addbook_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbook_btnActionPerformed(evt);
            }
        });

        updateBook_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        updateBook_btn.setText("Update Book");
        updateBook_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBook_btnActionPerformed(evt);
            }
        });

        removeBook_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        removeBook_btn.setText("Remove Book");
        removeBook_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBook_btnActionPerformed(evt);
            }
        });

        searchBook_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        searchBook_btn.setText("Search Book");
        searchBook_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBook_btnActionPerformed(evt);
            }
        });

        addbook_btn1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addbook_btn1.setText("Show Books");
        addbook_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbook_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchBook_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeBook_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBook_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back_btn)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(addbook_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addbook_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back_btn)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addbook_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addbook_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateBook_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeBook_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBook_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        Admin_Dashboard adminDashboard = new Admin_Dashboard();
        adminDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void addbook_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbook_btnActionPerformed
        Add_Book addBook = new Add_Book();
        addBook.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addbook_btnActionPerformed

    private void searchBook_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBook_btnActionPerformed
        Search_Book searchBook = new Search_Book();
        searchBook.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchBook_btnActionPerformed

    private void updateBook_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBook_btnActionPerformed
        Update_Book updateBook = new Update_Book();
        updateBook.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateBook_btnActionPerformed

    private void removeBook_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBook_btnActionPerformed
        Remove_book removebook = new Remove_book();
        removebook.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_removeBook_btnActionPerformed

    private void addbook_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbook_btn1ActionPerformed
        Show_Books showbooks = new Show_Books();
        showbooks.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addbook_btn1ActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbook_btn;
    private javax.swing.JButton addbook_btn1;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton removeBook_btn;
    private javax.swing.JButton searchBook_btn;
    private javax.swing.JButton updateBook_btn;
    // End of variables declaration//GEN-END:variables
}
