
package librarymanagementsystem.adminDashboard_Folder;

import librarymanagementsystem.adminDashboard_Folder.Manage_Books;
import librarymanagementsystem.adminDashboard_Folder.Manage_Users;
import javax.swing.SwingUtilities;


public class Admin_Dashboard extends javax.swing.JFrame {
    


    public Admin_Dashboard() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageFines_btn = new javax.swing.JButton();
        manageBooks_btn = new javax.swing.JButton();
        manageUsers_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        manageUsers_btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 40)); // NOI18N
        jLabel1.setText("Admin Dashboard");

        manageFines_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        manageFines_btn.setText("Manage Fines");
        manageFines_btn.setFocusable(false);
        manageFines_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFines_btnActionPerformed(evt);
            }
        });

        manageBooks_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        manageBooks_btn.setText("Manage Books");
        manageBooks_btn.setFocusable(false);
        manageBooks_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBooks_btnActionPerformed(evt);
            }
        });

        manageUsers_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        manageUsers_btn.setText("Manage User");
        manageUsers_btn.setFocusable(false);
        manageUsers_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsers_btnActionPerformed(evt);
            }
        });

        logout_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(255, 0, 51));
        logout_btn.setText("Logout");
        logout_btn.setFocusable(false);
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        manageUsers_btn1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        manageUsers_btn1.setText("Borrow Requests");
        manageUsers_btn1.setFocusable(false);
        manageUsers_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsers_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(manageFines_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageBooks_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageUsers_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageUsers_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageBooks_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageUsers_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageFines_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageUsers_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageFines_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFines_btnActionPerformed
//        manageFines.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_manageFines_btnActionPerformed

    private void manageUsers_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsers_btnActionPerformed
        Manage_Users manageUsers = new Manage_Users();
        manageUsers.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageUsers_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        Admin_Login login = new Admin_Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_btnActionPerformed

    private void manageBooks_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBooks_btnActionPerformed
        Manage_Books manageBooks = new Manage_Books();
        manageBooks.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageBooks_btnActionPerformed

    private void manageUsers_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsers_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageUsers_btn1ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new Admin_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton manageBooks_btn;
    private javax.swing.JButton manageFines_btn;
    private javax.swing.JButton manageUsers_btn;
    private javax.swing.JButton manageUsers_btn1;
    // End of variables declaration//GEN-END:variables
}
